<?php

declare(strict_types=1);

namespace Mgrunder\CreateCluster;

use InvalidArgumentException;

final class StartScriptGenerator
{
    public function generate(CommandLineOptions $options): string
    {
        if ($options->action !== 'start') {
            throw new InvalidArgumentException('--gen-script can only be used with start.');
        }

        $groupSize = $options->replicas + 1;
        if ($groupSize <= 0) {
            throw new InvalidArgumentException('replicas+1 must be greater than zero.');
        }

        if (count($options->ports) === 0) {
            throw new InvalidArgumentException('Cannot generate a start script without any ports.');
        }

        if (count($options->ports) % $groupSize !== 0) {
            throw new InvalidArgumentException(sprintf(
                'Node count (%d) must be divisible by replicas+1 (%d).',
                count($options->ports),
                $groupSize,
            ));
        }

        $masters = (int) (count($options->ports) / $groupSize);
        if ($masters < 3) {
            throw new InvalidArgumentException(sprintf('Need at least 3 masters, got %d.', $masters));
        }

        $lines = [
            '#!/usr/bin/env bash',
            'set -Eeuo pipefail',
            '',
            'REQUESTED_REDIS_SERVER=' . $this->quote($options->redisBinary),
            'REQUESTED_REDIS_CLI=' . $this->quote($options->redisCliBinary),
            'STATE_DIR_ROOT=' . $this->quote($options->stateDir),
            'ANNOUNCE_IP=' . $this->quote($options->announceIp ?? ''),
            'TLS_ENABLED=' . ($options->tls ? '1' : '0'),
            'TLS_DAYS=' . (string) $options->tlsDays,
            'TLS_RSA_BITS=' . (string) $options->tlsRsaBits,
            'REPLICAS=' . (string) $options->replicas,
            'CLUSTER_CREATE_HOST=' . $this->quote($options->announceIp ?: '127.0.0.1'),
            'START_SUCCESSFUL=0',
            'CLUSTER_DIR=""',
            'CA_CERT=""',
            'SERVER_CERT=""',
            'SERVER_KEY=""',
            'TAIL_BIN=""',
            '',
        ];

        array_push($lines, ...$this->buildArrayAssignment(
            'PORTS',
            array_map(static fn (int $port): string => (string) $port, $options->ports),
        ));
        $lines[] = '';

        array_push($lines, ...$this->buildArrayAssignment('START_SERVER_ARGS', $options->startServerArgs));
        $lines[] = '';

        array_push($lines, ...[
            'STARTED_PORTS=()',
            '',
            'step() { printf \'[..] %s\n\' "$1"; }',
            'info() { printf \'[i] %s\n\' "$1"; }',
            'success() { printf \'[ok] %s\n\' "$1"; }',
            'warn() { printf \'[!] %s\n\' "$1"; }',
            'error() { printf \'[error] %s\n\' "$1" >&2; }',
            '',
            'die() {',
            '  error "$1"',
            '  exit 1',
            '}',
            '',
            'on_error() {',
            '  local exit_code=$?',
            '  local line_no=$1',
            '  local command=$2',
            '  error "Command failed on line ${line_no}: ${command}"',
            '  cleanup_on_failure',
            '  exit "$exit_code"',
            '}',
            '',
            'trap \'on_error ${LINENO} "$BASH_COMMAND"\' ERR',
            '',
            'resolve_executable() {',
            '  local label=$1',
            '  local requested=$2',
            '  local resolved',
            '',
            '  if [[ "$requested" == *"/"* ]]; then',
            '    [[ -f "$requested" ]] || die "${label} executable not found: ${requested}"',
            '    [[ -x "$requested" ]] || die "${label} is not executable: ${requested}"',
            '    printf \'%s\n\' "$requested"',
            '    return 0',
            '  fi',
            '',
            '  resolved="$(command -v "$requested" 2>/dev/null || true)"',
            '  [[ -n "$resolved" ]] || die "${label} executable not found in PATH: ${requested}"',
            '  [[ -x "$resolved" ]] || die "${label} is not executable: ${resolved}"',
            '  printf \'%s\n\' "$resolved"',
            '}',
            '',
            'require_tool() {',
            '  local tool=$1',
            '  command -v "$tool" >/dev/null 2>&1 || die "Required command not found in PATH: ${tool}"',
            '}',
            '',
            'ensure_writable_directory() {',
            '  local path=$1',
            '  mkdir -p "$path"',
            '  [[ -d "$path" ]] || die "Expected directory does not exist: ${path}"',
            '  [[ -w "$path" ]] || die "Directory is not writable: ${path}"',
            '}',
            '',
            'assert_port_available() {',
            '  local port=$1',
            '  if (echo >/dev/tcp/127.0.0.1/"$port") >/dev/null 2>&1; then',
            '    die "Port ${port} is already in use."',
            '  fi',
            '}',
            '',
            'wait_for_port_to_close() {',
            '  local port=$1',
            '  local deadline=$((SECONDS + 5))',
            '',
            '  while (( SECONDS < deadline )); do',
            '    if ! (echo >/dev/tcp/127.0.0.1/"$port") >/dev/null 2>&1; then',
            '      return 0',
            '    fi',
            '',
            '    sleep 0.1',
            '  done',
            '',
            '  warn "Port ${port} is still accepting connections after shutdown."',
            '}',
            '',
            'show_node_log_tail() {',
            '  local port=$1',
            '  local log_path="${CLUSTER_DIR}/node-${port}/redis.log"',
            '',
            '  if [[ -n "$TAIL_BIN" && -f "$log_path" ]]; then',
            '    warn "Last 20 log lines from ${log_path}:"',
            '    "$TAIL_BIN" -n 20 "$log_path" >&2 || true',
            '  fi',
            '}',
            '',
            'redis_cli_node() {',
            '  local port=$1',
            '  shift || true',
            '  local args=()',
            '',
            '  if (( TLS_ENABLED == 1 )); then',
            '    args+=(--tls)',
            '    if [[ -n "$CA_CERT" ]]; then',
            '      args+=(--cacert "$CA_CERT")',
            '    fi',
            '  fi',
            '',
            '  "$REDIS_CLI_BIN" "${args[@]}" -h 127.0.0.1 -p "$port" "$@"',
            '}',
            '',
            'wait_for_ready() {',
            '  local port=$1',
            '  local deadline=$((SECONDS + 10))',
            '',
            '  while (( SECONDS < deadline )); do',
            '    if redis_cli_node "$port" PING >/dev/null 2>&1; then',
            '      return 0',
            '    fi',
            '',
            '    sleep 0.1',
            '  done',
            '',
            '  show_node_log_tail "$port"',
            '  die "Timed out waiting for Redis node at port ${port}."',
            '}',
            '',
            'cleanup_on_failure() {',
            '  if (( START_SUCCESSFUL == 1 )); then',
            '    return 0',
            '  fi',
            '',
            '  if (( ${#STARTED_PORTS[@]} > 0 )); then',
            '    warn "Start failed; shutting down any nodes that were launched."',
            '    for port in "${STARTED_PORTS[@]}"; do',
            '      info "Sending SHUTDOWN to port ${port}"',
            '      redis_cli_node "$port" SHUTDOWN NOSAVE >/dev/null 2>&1 || true',
            '      wait_for_port_to_close "$port" || true',
            '    done',
            '  fi',
            '',
            '  if [[ -n "$CLUSTER_DIR" ]]; then',
            '    warn "Cluster state directory preserved at ${CLUSTER_DIR} for inspection."',
            '  fi',
            '}',
            '',
            'generate_tls_material() {',
            '  local tls_dir="${CLUSTER_DIR}/tls"',
            '  local ca_key="${tls_dir}/ca.key"',
            '  local ca_crt="${tls_dir}/ca.crt"',
            '  local server_key="${tls_dir}/server.key"',
            '  local server_csr="${tls_dir}/server.csr"',
            '  local server_crt="${tls_dir}/server.crt"',
            '  local extension="${tls_dir}/server.ext"',
            '',
            '  mkdir -p "$tls_dir"',
            '  chmod 700 "$tls_dir"',
            '',
            '  {',
            '    printf \'%s\n\' \'[v3_req]\'',
            '    printf \'%s\n\' \'subjectAltName=@alt_names\'',
            '    printf \'%s\n\' \'[alt_names]\'',
            '    printf \'%s\n\' \'IP.1=127.0.0.1\'',
            '    printf \'%s\n\' \'DNS.1=localhost\'',
            '    if [[ -n "$ANNOUNCE_IP" && "$ANNOUNCE_IP" != "127.0.0.1" ]]; then',
            '      printf \'IP.2=%s\n\' "$ANNOUNCE_IP"',
            '    fi',
            '  } > "$extension"',
            '',
            '  step "Generating ephemeral TLS material"',
            '  "$OPENSSL_BIN" genrsa -out "$ca_key" "$TLS_RSA_BITS"',
            '  "$OPENSSL_BIN" req -x509 -new -nodes -key "$ca_key" -sha256 -days "$TLS_DAYS" -subj /CN=redis-ephemeral-ca -out "$ca_crt"',
            '  "$OPENSSL_BIN" genrsa -out "$server_key" "$TLS_RSA_BITS"',
            '  "$OPENSSL_BIN" req -new -key "$server_key" -subj /CN=redis-ephemeral-server -out "$server_csr"',
            '  "$OPENSSL_BIN" x509 -req -in "$server_csr" -CA "$ca_crt" -CAkey "$ca_key" -CAcreateserial -out "$server_crt" -days "$TLS_DAYS" -sha256 -extfile "$extension" -extensions v3_req',
            '',
            '  CA_CERT="$ca_crt"',
            '  SERVER_CERT="$server_crt"',
            '  SERVER_KEY="$server_key"',
            '  success "TLS material generated"',
            '}',
            '',
            'write_node_config() {',
            '  local port=$1',
            '  local node_dir="${CLUSTER_DIR}/node-${port}"',
            '  local config_path="${node_dir}/redis.conf"',
            '',
            '  mkdir -p "$node_dir"',
            '',
            '  {',
            '    printf \'%s\n\' \'cluster-enabled yes\'',
            '    printf \'cluster-config-file %s\n\' "${node_dir}/nodes.conf"',
            '    printf \'dir %s\n\' "$node_dir"',
            '    printf \'%s\n\' \'dbfilename dump.rdb\'',
            '    printf \'%s\n\' \'appendonly no\'',
            '    printf \'%s\n\' \'save ""\'',
            '    printf \'%s\n\' \'daemonize yes\'',
            '    printf \'pidfile %s\n\' "${node_dir}/redis.pid"',
            '    printf \'logfile %s\n\' "${node_dir}/redis.log"',
            '    printf \'%s\n\' \'protected-mode no\'',
            '    printf \'%s\n\' \'bind 127.0.0.1\'',
            '',
            '    if (( TLS_ENABLED == 1 )); then',
            '      printf \'%s\n\' \'port 0\'',
            '      printf \'tls-port %s\n\' "$port"',
            '      printf \'tls-cert-file %s\n\' "$SERVER_CERT"',
            '      printf \'tls-key-file %s\n\' "$SERVER_KEY"',
            '      printf \'tls-ca-cert-file %s\n\' "$CA_CERT"',
            '      printf \'%s\n\' \'tls-auth-clients no\'',
            '      printf \'%s\n\' \'tls-replication yes\'',
            '      printf \'%s\n\' \'tls-cluster yes\'',
            '      printf \'%s\n\' \'cluster-announce-port 0\'',
            '      printf \'cluster-announce-tls-port %s\n\' "$port"',
            '    else',
            '      printf \'port %s\n\' "$port"',
            '    fi',
            '',
            '    if [[ -n "$ANNOUNCE_IP" ]]; then',
            '      printf \'cluster-announce-ip %s\n\' "$ANNOUNCE_IP"',
            '    fi',
            '  } > "$config_path"',
            '',
            '  printf \'%s\n\' "$config_path"',
            '}',
            '',
            'step "Validating required executables and runtime prerequisites"',
            'REDIS_SERVER_BIN="$(resolve_executable redis-server "$REQUESTED_REDIS_SERVER")"',
            'REDIS_CLI_BIN="$(resolve_executable redis-cli "$REQUESTED_REDIS_CLI")"',
            'TAIL_BIN="$(resolve_executable tail tail)"',
            'require_tool mktemp',
            'require_tool mkdir',
            'require_tool chmod',
            'require_tool head',
            'require_tool sleep',
            '',
            'if (( TLS_ENABLED == 1 )); then',
            '  OPENSSL_BIN="$(resolve_executable openssl openssl)"',
            'else',
            '  OPENSSL_BIN=""',
            'fi',
            '',
            '(( ${#PORTS[@]} > 0 )) || die "No ports configured for generated start script."',
            'GROUP_SIZE=$((REPLICAS + 1))',
            '(( GROUP_SIZE > 0 )) || die "replicas+1 must be greater than zero."',
            'if (( ${#PORTS[@]} % GROUP_SIZE != 0 )); then',
            '  die "Node count (${#PORTS[@]}) must be divisible by replicas+1 (${GROUP_SIZE})."',
            'fi',
            '',
            'MASTERS=$(( ${#PORTS[@]} / GROUP_SIZE ))',
            'if (( MASTERS < 3 )); then',
            '  die "Need at least 3 masters, got ${MASTERS}."',
            'fi',
            '',
            'for port in "${PORTS[@]}"; do',
            '  assert_port_available "$port"',
            'done',
            '',
            'ensure_writable_directory "$STATE_DIR_ROOT"',
            'success "Preflight checks passed"',
            '',
            'CLUSTER_DIR="$(mktemp -d "${STATE_DIR_ROOT%/}/cluster-XXXXXXXX")"',
            'info "Using cluster state directory ${CLUSTER_DIR}"',
            'info "Server: $("$REDIS_SERVER_BIN" --version 2>&1 | head -n 1)"',
            '',
            'if (( TLS_ENABLED == 1 )); then',
            '  generate_tls_material',
            'fi',
            '',
            'for port in "${PORTS[@]}"; do',
            '  step "Starting Redis node on port ${port}"',
            '  config_path="$(write_node_config "$port")"',
            '  "$REDIS_SERVER_BIN" "$config_path" "${START_SERVER_ARGS[@]}"',
            '  wait_for_ready "$port"',
            '  STARTED_PORTS+=("$port")',
            '  success "Redis node ${port} is ready"',
            'done',
            '',
            'step "Creating cluster topology and assigning slots"',
            'cluster_create_command=("$REDIS_CLI_BIN")',
            'if (( TLS_ENABLED == 1 )); then',
            '  cluster_create_command+=(--tls)',
            '  cluster_create_command+=(--cacert "$CA_CERT")',
            'fi',
            'cluster_create_command+=(--cluster create)',
            'for port in "${PORTS[@]}"; do',
            '  cluster_create_command+=("${CLUSTER_CREATE_HOST}:${port}")',
            'done',
            'cluster_create_command+=(--cluster-replicas "$REPLICAS" --cluster-yes)',
            '"${cluster_create_command[@]}"',
            'success "Cluster topology created"',
            '',
            'START_SUCCESSFUL=1',
            'success "Started cluster in ${CLUSTER_DIR}"',
            'info "Ports: ${PORTS[*]}"',
            'if (( TLS_ENABLED == 1 )); then',
            '  info "CA cert: ${CA_CERT}"',
            'fi',
        ]);

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    /**
     * @param list<string> $values
     * @return list<string>
     */
    private function buildArrayAssignment(string $name, array $values): array
    {
        $lines = [$name . '=('];
        foreach ($values as $value) {
            $lines[] = '  ' . $this->quote($value);
        }
        $lines[] = ')';

        return $lines;
    }

    private function quote(string $value): string
    {
        return escapeshellarg($value);
    }
}
